version: "2"
services:
  php:
    build: 
      context: './php/'
    volumes:
      - www:/var/www/html/
  apache:
    build:
      context: './apache/'
    depends_on:
      - php
      - db
    ports:
      - "8080:80"
    volumes:
      - www:/var/www/html/
  db:
    image: mariadb:latest
    volumes:
      - data:/var/lib/mysql
    env_file:
     - 'default.docker-env'
  redis:
    image: redis:5
    volumes:
      - redis:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - 1884:1883

volumes:
  data:
    driver: local
  www:
    driver: local
  redis:
    driver: local
