version: "2"
services:
  php:
    build: './php/' 
    volumes:
      - www:/var/www/
      - phpfina:/var/opt/emoncms/phpfina
      - phptimeseries:/var/opt/emoncms/phptimeseries
      - emoncms-log:/var/log/emoncms   
      - var-lock:/var/lock
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=emoncms"
      - "MYSQL_USER=emoncms"
      - "MYSQL_PASSWORD=emoncms"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

      - "REDIS_ENABLED=true"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_PREFIX='emoncms'"

      - "MQTT_ENABLED=true"
      - "MQTT_HOST=mqtt"
      - "MQTT_USER=emonpi"
      - "MQTT_PASSWORD=emonpimqtt2016"
      - "MQTT_BASETOPIC=emon"
      - "MQTT_PORT=1884"

      - "PHPFINA_DIR=/var/opt/emoncms/phpfina/"
      - "PHPTIMESERIES_DIR=/var/opt/emoncms/phptimeseries/"
      - "PREDISBUFFER_ENABLED=true"
      - "EMONCMS_DIR=/opt/emoncms"
      - "OPENENERGYMONITOR_DIR=/opt/openenergymonitor"
        
      - "DEFAULT_LANG=cy_GB"

      - "LOG_ENABLED=true"
      - "LOG_LOCATION=/var/log/emoncms"
      - "LOG_LEVEL=1"

      - "FEEDVIEW_PATH=vis/rawdata?feedid="

    ports:
      - "9000:9000"
  apache:
    build:
      context: './apache/'
      args:
        apache_port: 80
    depends_on:
      - php
      - db
    environment:
      - "APACHE_PORT=${APACHE_PORT}"
    volumes:
      - www:/var/www/
  db:
    image: mariadb:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=emoncms"
      - "MYSQL_USER=emoncms"
      - "MYSQL_PASSWORD=emoncms"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
  redis:
    image: redis:5
    volumes:
      - redis:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      - "REDIS_ENABLED=true"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_PREFIX='emoncms'"
  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - 1884:1883
      
  emoncms_mqtt:
    build:
      context: './emoncms_mqtt/'
    depends_on:
      - php
      - db
    volumes:
      - www:/var/www/
    command: sh -c "sleep 5; SCRIPT_FILENAME=/var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php REQUEST_METHOD=GET cgi-fcgi -bind -connect php:9000"
    
  emoncms_feedwriter:
    build: './emoncms_feedwriter'
    depends_on:
      - php
    command: sh -c "sleep 5; SCRIPT_FILENAME=/var/www/emoncms/scripts/feedwriter.php REQUEST_METHOD=GET cgi-fcgi -bind -connect php:9000"
    # command: ["tail", "-f", "/dev/null"]
           
volumes:
  db:
  www:
  redis:
  phpfina:
  phptimeseries:
  emoncms-log:
  var-lock:
